### ISSUE TITLE
Wrong syntax color at wrong place

### ISSUE THREAD

**Issue by coujean99** [ericgomez/vscode-php-string-syntax#3]
So, I was about to create this same extension for myself until I found yours. Great job man. Simple and efficient.

However by using it, I discovered that it does not only show HTML tags in php strings, but also in "plain" HTML.

When writing some text containing single/double quote in a simple HTML tags, it does this:

![Image](https://github.com/user-attachments/assets/4141bf6e-e910-46cb-86ba-56eaeeeeab47)

Also, do you know if it could be possible to add intelliSense into your extension ? That would be freacking awesome!

Have a nice day my friend!

-JC

**Comment by ericgomez** [comment]
Hi JC,

Thank you so much for taking the time to report the issue.

You're absolutely right, there was a bug where apostrophes in contractions were incorrectly interpreted as string delimiters. This has been fixed in the latest version of the extension.

If you update to the most recent version, it should now handle those cases properly. Please let me know if you notice anything else!

As for IntelliSense, that's definitely something I’d love to explore. It’s a bit more involved, but I’ve noted it as a potential feature for a future update.

**Comment by coujean99** [comment]
Hello Eric,

Thanks for your reply.

I’ve updated to version *0.1.4*, and yes, I did notice something else 🙂 There’s still an issue occurring in some files, although it seems pretty niche.

For example, here’s a snippet directly from my `index.php`. It’s a small detail, but I thought you should know.

With the extension **enabled**:
![Image](https://github.com/user-attachments/assets/5888321d-08ab-4c32-82a8-e628a4b4e696)

<br>

With the extension **disabled**:
![Image](https://github.com/user-attachments/assets/d8b72ef8-b9f4-4d89-86e3-a12fe912651f)

<br>

Here is an other small syntax problem:
![Image](https://github.com/user-attachments/assets/e7f3f1f4-b427-461a-a044-32c5b0d6aabf)

<br>

Also, it looks like escape characters *( \\ )* used before accented characters in single-quoted strings are causing syntax highlighting issues. Here’s an example from our `fr.php` file:
![Image](https://github.com/user-attachments/assets/27ee44f0-b732-408b-a80a-9f1668e20431)

After that line, the rest of the file becomes heavily broken — even a regular word is incorrectly recognized as a function 😛

<br>
<br>

I hope this helps.

Have a great day,
JC

**Comment by ericgomez** [comment]
Hey JC,

Thanks again for pointing out the issue.

I checked those scenarios and fixed them. I’ve also uploaded a new version with the updates.

![Image](https://github.com/user-attachments/assets/4f224a7b-9312-4216-9204-95043fc971b4)

Let me know if you spot anything else! 🙂

Have a great day.
